### ISSUE TITLE
Idea project setup

### ISSUE THREAD

**Issue by frickua** [frickua/music-organizer#1]
Need to setup idea project.

**Comment by frickua** [comment]
Include PostgreSQL dependencies.

**Comment by SkoblyaOleksandr** [comment]
(sad smile)

**Comment by SkoblyaOleksandr** [comment]
what idea we will use? what about it's license ?

**Comment by frickua** [comment]
Idea CE should be enough.

**Comment by SkoblyaOleksandr** [comment]
what version of postgre will use? latest one?
